### ISSUE TITLE
Uninstalling will let some files in the computer

### ISSUE THREAD

**Issue by RisedSky** [PreMiD/PreMiD#205]
**Describe the bug**
When uninstalling PreMiD, using windows will cause the file 'Update.exe' in the AppData/Local/premid folder
A big issue is that it doesn't remove from the automatic start (image in proof) 

![image](https://user-images.githubusercontent.com/23197999/63594951-19dbcb80-c5b8-11e9-8b05-d4be085cd72d.png)

![image](https://user-images.githubusercontent.com/23197999/63594842-d1241280-c5b7-11e9-8b77-0fb13066a915.png)

**To Reproduce**
1. Uninstall PreMiD

**Expected behavior**
It should not let files and automatic start in the computer

**Desktop (please complete the following information):**
 - OS: W10 1903 Family

**Comment by Noboruu** [comment]
Is this really a premid issue?
From what I've been looking at premid doesn't use any specific uninstaller, it's windows taking care of it, it's common for uninstalled software to leave traces behind (basically every single one does), especially when it's windows itself handling the uninstall process.
I was looking into it and update.exe is left behind for sure, but it doesn't produce any adverse effect, no error on startup, and it seems like it WAS removed from startup since I don't find anything regarding it in neither msconfig or the task manager.

**Comment by Timeraa** [comment]
We partnered up with InstallBuilder and we use their installers & updaters. It was an issue on my side that it left some files behind (except appdata, added it to the uninstaller too). The next release should normally uninstall everything.
