### ISSUE TITLE
Update failure.

### ISSUE THREAD

**Issue by smolyoshino** [PreMiD/PreMiD#350]
**Describe the bug**
PreMiD bugs me saying there's an update available, alright. sure.
But...it...can't update itself? No matter what I try.

**To Reproduce**
1. Right click it to update, https://zoe.is-ne.at/Frf27f.png this happens.
2. Try to run the command in cmd, nothing happens.
3. Run the updater standalone, says there's no update available https://zoe.is-ne.at/AjpIZ9.png

**Expected behavior**
The app should update?

**Screenshots**
Screenshots attached above in reproduction steps. (The link is a custom sharex file hoster, it's not a shady site, the link is from https://sxcu.net/ )

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Latest

**Additional context**
With the failed to run command window open, it doesn't bother me about the update, but when I close it, it bothers me about the update frequently, even though it can't update itself.

**Comment by eggsywashere** [comment]
Hello @smolyoshino 👋 

We're (or they are, since I don't have a permission on this repo/I'm a moderator in PreMiD's Discord) aware of the issue and we're currently working to fix it! We are already started testing new updater on more machines than the old time we tested on. 

Currently, the only way you can get rid of that issue is to **uninstall the app** and then **install it again**. Please keep in mind that this way won't fix the error, it's just a temporary solution; this means you'll have to reinstall the application again once we get updater to work again. You can use the links below (one is from the official URL, other one is from the Discord's repo) and if downloading process is slow, please wait until it finishes. We're sorry for this confusion.

[Official URL](https://dl.premid.app/PreMiD-installer.exe) - [Installer File from Discord's CDN](https://cdn.discordapp.com/attachments/518467470894563345/673290559506350121/PreMiD-installer.exe)

**Comment by Timeraa** [comment]
Should be fixed in the latest update 🤞

**Comment by smolyoshino** [comment]
alright, thanks for the response!
