### ISSUE TITLE
Trojan Virustotal scan!

### ISSUE THREAD

**Issue by adilaxmdv** [PreMiD/PreMiD#944]
**Describe the bug**

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

![image](https://user-images.githubusercontent.com/74068841/225363929-f32ed3af-aa62-4b5a-afe5-189eecfb3d7a.png)

Why Virustotal show trojan ?

Virustotal : 8244204c1226a24d2842412ce429a09659ab66bcd7c4cb4f072a786b878ecbc4

**Comment by adilaxmdv** [comment]
hey!...

**Comment by WindofNortheast** [comment]
I guess we won't get an answer for a long time

**Comment by adilaxmdv** [comment]
@WindofNortheast  why ??

**Comment by WindofNortheast** [comment]
It's been 17 hours and still no response. I guess the developers don't care much

**Comment by DarkVillager** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior: 1. 2. 3.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.
> 
> ![image](https://user-images.githubusercontent.com/74068841/225363929-f32ed3af-aa62-4b5a-afe5-189eecfb3d7a.png)
> 
> Why Virustotal show trojan ?
> 
> Virustotal : 8244204c1226a24d2842412ce429a09659ab66bcd7c4cb4f072a786b878ecbc4

@Bas950 @Timeraa

**Comment by adilaxmdv** [comment]
@DarkVillager  you are okay ?

**Comment by Bas950** [comment]
You are literally viewing the source code of it in this repository, if you can find the Trojan let us know, but these websites have a bunch of false positives for all sorts of tools, sadly ours included.

I can say with ease that this is a false positive, otherwise I sure the internet as a whole wouldn't have let us get to 500k users. 
Thank you for reporting tho, we will report the false positive to them as well to hopefully get it removed.

We are sorry that you had to wait for a "long" time, we all do this voluntary and have irl work during the day. Hence why it may take a few to get a response.
